/*
 * Does this file actually carry a content credential?
 *
 * Same rule as ffprobe and duration: PROBE, NEVER BELIEVE. A model descriptor
 * saying `c2pa: true` is the vendor's claim about their product, not a fact
 * about the bytes in front of us — and the whole "was it stripped" chain is
 * built on top of it (EU AI Act Art. 50 has applied since 2 Aug 2026).
 *
 * This DETECTS a manifest; it does not validate a signature. Validation needs
 * the C2PA trust list and is a different job — so nothing here ever says
 * "verified", only "carries one".
 *
 * Detection is container-independent on purpose. A C2PA manifest store is a
 * JUMBF superbox (ISO/IEC 19566-5): `jumb`, then a `jumd` description box whose
 * label is `c2pa`. Requiring all three in sequence is what keeps false
 * positives near zero, which matters more than catching every last file: saying
 * "absent" about a signed file under-claims, saying "signed" about an unsigned
 * one is a lie to a customer about their disclosure.
 */

/** JUMBF superbox type, its description box, and the C2PA label. */
const JUMB = Buffer.from("jumb", "ascii");
const JUMD = Buffer.from("jumd", "ascii");
const C2PA = Buffer.from("c2pa", "ascii");

/** `jumd` follows `jumb` almost immediately; the label follows the box UUID. */
const JUMD_WINDOW = 16;
const LABEL_WINDOW = 64;

/** Manifests sit near one end. A 500MB render is not worth a full linear scan. */
export const SCAN_HEAD_BYTES = 8 * 1024 * 1024;
export const SCAN_TAIL_BYTES = 2 * 1024 * 1024;

export type CredentialScan = {
  present: boolean;
  /** Byte offset of the JUMBF marker, for the audit trail. Null when not found. */
  at: number | null;
  /** True when the middle of a large file was skipped, so `false` is not proof. */
  bounded: boolean;
};

/** A JUMBF superbox labelled `c2pa`, or -1. */
function findManifest(buf: Buffer, from = 0): number {
  let i = buf.indexOf(JUMB, from);
  while (i !== -1) {
    const jumd = buf.indexOf(JUMD, i + 4);
    if (jumd !== -1 && jumd - i <= JUMD_WINDOW) {
      const label = buf.indexOf(C2PA, jumd + 4);
      if (label !== -1 && label - jumd <= LABEL_WINDOW) return i;
    }
    i = buf.indexOf(JUMB, i + 4);
  }
  return -1;
}

export function scanForCredential(bytes: Buffer): CredentialScan {
  const bounded = bytes.byteLength > SCAN_HEAD_BYTES + SCAN_TAIL_BYTES;
  if (!bounded) {
    const at = findManifest(bytes);
    return { present: at !== -1, at: at === -1 ? null : at, bounded: false };
  }

  const head = findManifest(bytes.subarray(0, SCAN_HEAD_BYTES));
  if (head !== -1) return { present: true, at: head, bounded: true };

  const tailFrom = bytes.byteLength - SCAN_TAIL_BYTES;
  const tail = findManifest(bytes.subarray(tailFrom));
  return { present: tail !== -1, at: tail === -1 ? null : tailFrom + tail, bounded: true };
}

export type CredentialState = "signed" | "stripped" | "absent";

/**
 * What to record for freshly generated bytes, and where the vendor's claim and
 * the file disagree. A disagreement is reported, never quietly resolved.
 */
export function credentialForOutput(bytes: Buffer, claimed: boolean): { state: CredentialState; mismatch: string | null } {
  const scan = scanForCredential(bytes);
  if (scan.present) {
    return { state: "signed", mismatch: claimed ? null : "the model doesn't claim content credentials, but the file carries one" };
  }
  // Bounded scans under-claim rather than over-claim; say so instead of hiding it.
  const why = scan.bounded ? " (only the start and end of the file were scanned)" : "";
  return { state: "absent", mismatch: claimed ? `the model claims content credentials, but none is present in the file${why}` : null };
}

/**
 * What to record for bytes WE produced from a source. Re-encoding strips a
 * manifest, so a signed source that comes out bare is `stripped` — the fact the
 * disclosure duty turns on, and the reason it is recorded rather than lost.
 */
export function credentialForDerived(bytes: Buffer, source: CredentialState | undefined): CredentialState {
  if (scanForCredential(bytes).present) return "signed";
  return source === "signed" || source === "stripped" ? "stripped" : "absent";
}
