/*
 * What to tell someone about the content credential on a file they are about to
 * publish.
 *
 * Four things get conflated constantly (docs/research/ai-media-2026.md §12) and
 * this is only ONE of them: the machine-readable manifest in the file. It is not
 * the network's AI label (lib/disclosure.ts), not an invisible watermark, and
 * not the legal duty itself — a file can carry all four independently.
 *
 * The reason it earns a message: TikTok and Meta auto-label from the credential.
 * A pipeline that re-encodes AI video and says nothing has REMOVED the
 * disclosure the model vendor attached, which is worse than never generating it.
 * So we say what happened. Warnings, not blocks — the caption label is a real
 * disclosure, and re-signing is not available yet (12.5, needs a certificate).
 */
import type { AssetProvenance } from "@/db/schema/assets";

export type CredentialSubject = {
  fileName: string;
  generatedByAi: boolean;
  provenance: AssetProvenance | null;
};

export type CredentialIssue = { severity: "warning"; code: string; message: string };

const AUTO_LABEL = "Networks that auto-label from credentials won't recognise it, so the disclosure in your caption is the only label it carries.";

/**
 * `stripped` is the one we caused, so it is worded as something that happened
 * rather than something that is missing.
 */
export function credentialIssue(a: CredentialSubject): CredentialIssue | null {
  const state = a.provenance?.c2pa;
  if (state === "signed") return null;

  if (state === "stripped") {
    return {
      severity: "warning",
      code: "credential_stripped",
      message: `“${a.fileName}” arrived with a content credential and lost it when we re-encoded the file. ${AUTO_LABEL}`,
    };
  }
  if (a.generatedByAi) {
    return {
      severity: "warning",
      code: "credential_absent",
      message: `“${a.fileName}” was generated by AI and carries no content credential. ${AUTO_LABEL}`,
    };
  }
  return null;
}

/** One line per file that has something to say. Silent when everything is fine. */
export const credentialIssues = (assets: CredentialSubject[]): CredentialIssue[] =>
  assets.flatMap((a) => credentialIssue(a) ?? []);
