/*
 * Vendor output → an asset in the library.
 *
 * One rule: PROBE, NEVER BELIEVE. The vendor's stated duration is a claim; the
 * file is the fact. Disagreements are recorded, not hidden — a model that says
 * 8s and delivers 7.4s will fail a network's duration rule later, and this is
 * where that becomes visible.
 *
 * Generated bytes enter through exactly the same door as an upload: object
 * storage → asset row → asset.process. There is no second path.
 */
import { createHash } from "node:crypto";
import type { RawOutput } from "@rocketease/media";
import { db } from "@/db";
import { asset, type AssetKind, type RightsScope } from "@/db/schema/assets";
import { audit } from "@/lib/audit";
import { emit } from "@/lib/jobs/outbox";
import { newObjectKey, putObject } from "@/lib/storage";
import { credentialForOutput } from "./c2pa";
import { mismatches, probeBuffer, wholeSeconds } from "./probe";
import { sniffContainer } from "./sniff";

export type NormalizeActor = { organizationId: string; workspaceId: string; userId: string | null };

export type NormalizeInput = {
  actor: NormalizeActor;
  mediaJobId: string;
  modelKey: string;
  outputs: RawOutput[];
  /**
   * What the MODEL says it attaches, plus where this output came from. Whether a
   * credential is actually in the bytes is probed here, not taken on trust.
   */
  provenance: { claimsC2pa: boolean; watermark: string | null; chain: { action: string; adapter?: string; model?: string }[] };
  altText?: string | null;
  /**
   * What the output may be used for. A voice-over made under organic-only
   * consent is an organic-only asset, so the rights preflight blocks it from an
   * ad without anyone having to remember the consent record.
   */
  rightsScope?: RightsScope;
};

export type NormalizeResult = { assetIds: string[]; mismatches: string[] };

const fileName = (kind: AssetKind, extension: string, i: number) =>
  `ai-${kind}-${new Date().toISOString().slice(0, 10)}-${i + 1}${extension}`;

/** One asset per output, each queued for processing exactly like an upload. */
export async function normalizeOutputs(input: NormalizeInput): Promise<NormalizeResult> {
  const { actor } = input;
  const assetIds: string[] = [];
  const allMismatches: string[] = [];

  for (const [i, out] of input.outputs.entries()) {
    const buf = Buffer.from(out.bytes);

    // Sniffed from the bytes, not from a header we did not ask for.
    const sniffed = sniffContainer(buf);
    if (!sniffed) {
      allMismatches.push(`output ${i + 1}: unrecognised file format, not stored`);
      continue;
    }
    if (out.claimedMimeType && out.claimedMimeType !== sniffed.mimeType) {
      allMismatches.push(`output ${i + 1} type: claimed ${out.claimedMimeType}, file is ${sniffed.mimeType}`);
    }

    const { probe } = await probeBuffer(buf, `output${sniffed.extension}`);
    allMismatches.push(
      ...mismatches(probe, {
        durationSeconds: out.claimedDurationSeconds,
        width: out.claimedWidth,
        height: out.claimedHeight,
      }).map((m) => `output ${i + 1} ${m}`),
    );

    // Probe, never believe: the descriptor is the vendor's claim about their
    // product, not a fact about these bytes (EU AI Act Art. 50 turns on the file).
    const credential = credentialForOutput(buf, input.provenance.claimsC2pa);
    if (credential.mismatch) allMismatches.push(`output ${i + 1} provenance: ${credential.mismatch}`);

    const name = fileName(sniffed.kind, sniffed.extension, i);
    const key = newObjectKey(actor.organizationId, actor.workspaceId, "original", name);
    await putObject(key, buf, sniffed.mimeType);

    const id = await db.transaction(async (tx) => {
      const [row] = await tx
        .insert(asset)
        .values({
          organizationId: actor.organizationId,
          workspaceId: actor.workspaceId,
          kind: sniffed.kind,
          storageKey: key,
          fileName: name,
          mimeType: sniffed.mimeType,
          bytes: buf.byteLength,
          width: probe.width,
          height: probe.height,
          durationSeconds: wholeSeconds(probe.durationSeconds),
          checksumSha256: createHash("sha256").update(buf).digest("hex"),
          title: name.replace(/\.[^.]+$/, ""),
          altText: input.altText ?? null,
          uploadStatus: "processing",
          generatedByAi: true,
          generationModel: input.modelKey,
          mediaJobId: input.mediaJobId,
          provenance: { c2pa: credential.state, watermark: input.provenance.watermark, chain: input.provenance.chain },
          licenseSource: "ai_generated",
          rightsScope: input.rightsScope ?? "both",
          uploadedByUserId: actor.userId,
        })
        .returning({ id: asset.id });
      await emit(tx, "asset.process", { assetId: row.id }, {
        organizationId: actor.organizationId,
        workspaceId: actor.workspaceId,
        dedupeKey: `asset.process:${row.id}`,
      });
      return row.id;
    });

    assetIds.push(id);
    await audit({
      action: "asset.upload",
      actorUserId: actor.userId,
      organizationId: actor.organizationId,
      workspaceId: actor.workspaceId,
      targetType: "asset",
      targetId: id,
      summary: { after: { fileName: name, kind: sniffed.kind, bytes: buf.byteLength, generatedByAi: true, model: input.modelKey } },
    });
  }

  return { assetIds, mismatches: allMismatches };
}
