/*
 * Content library (content-model.md "Assets", requirements LIB-001/002).
 * Originals and renditions live in object storage; rows hold metadata,
 * rights, scan status, and accessibility text. Deletion is soft.
 */
import { sql } from "drizzle-orm";
import { boolean, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";
import { organization, user } from "./auth";
import { workspace } from "./app";

const id = (name = "id") =>
  text(name)
    .primaryKey()
    .default(sql`gen_random_uuid()`);
const now = (name: string) => timestamp(name, { withTimezone: true }).notNull().defaultNow();

export const ASSET_KINDS = ["image", "video", "document", "audio"] as const;
export type AssetKind = (typeof ASSET_KINDS)[number];
export const assetKind = pgEnum("asset_kind", ASSET_KINDS);

export const UPLOAD_STATUSES = ["pending", "processing", "ready", "failed"] as const;
export const uploadStatus = pgEnum("upload_status", UPLOAD_STATUSES);

export const RIGHTS_SCOPES = ["organic", "paid", "both"] as const;
/** What a licence covers. Organic rights rarely include paid (trends-2026 §4). */
export type RightsScope = (typeof RIGHTS_SCOPES)[number];

export const LICENSE_SOURCES = ["owned", "stock", "platform_library", "ai_generated"] as const;
/** Where an asset's rights come from. `platform_library` licences do not travel between networks. */
export type LicenseSource = (typeof LICENSE_SOURCES)[number];

/** What happened to the content credentials on the way through our pipeline. */
export type AssetProvenance = {
  c2pa: "signed" | "stripped" | "absent";
  watermark: string | null;
  /** Ordered: generated by model X, captions burned in, resized to 9:16. */
  chain: { action: string; adapter?: string; model?: string }[];
};

export const SCAN_STATUSES = ["pending", "clean", "infected", "error"] as const;
export const scanStatus = pgEnum("scan_status", SCAN_STATUSES);

export const folder = pgTable(
  "folder",
  {
    id: id(),
    organizationId: text("organization_id").notNull().references(() => organization.id, { onDelete: "cascade" }),
    workspaceId: text("workspace_id").notNull().references(() => workspace.id, { onDelete: "cascade" }),
    parentId: text("parent_id"),
    name: text("name").notNull(),
    createdAt: now("created_at"),
  },
  (t) => [index("folder_ws_idx").on(t.workspaceId, t.parentId)],
);

export const tag = pgTable(
  "tag",
  {
    id: id(),
    organizationId: text("organization_id").notNull().references(() => organization.id, { onDelete: "cascade" }),
    workspaceId: text("workspace_id").notNull().references(() => workspace.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    createdAt: now("created_at"),
  },
  (t) => [uniqueIndex("tag_ws_name_idx").on(t.workspaceId, t.name)],
);

/** Mirrors lib/media/references.ts REFERENCE_KINDS; kept here so the column is typed. */
export const REFERENCE_KINDS = ["product", "logo", "style", "talent"] as const;
export type ReferenceKind = (typeof REFERENCE_KINDS)[number];

export const asset = pgTable(
  "asset",
  {
    id: id(),
    organizationId: text("organization_id").notNull().references(() => organization.id, { onDelete: "cascade" }),
    workspaceId: text("workspace_id").notNull().references(() => workspace.id, { onDelete: "cascade" }),
    folderId: text("folder_id").references(() => folder.id, { onDelete: "set null" }),
    kind: assetKind("kind").notNull(),
    /** Object key of the original in STORAGE_BUCKET. */
    storageKey: text("storage_key").notNull(),
    fileName: text("file_name").notNull(),
    mimeType: text("mime_type").notNull(),
    bytes: integer("bytes"),
    width: integer("width"),
    height: integer("height"),
    durationSeconds: integer("duration_seconds"),
    checksumSha256: text("checksum_sha256"),
    title: text("title"),
    altText: text("alt_text"),
    caption: text("caption"),
    tagIds: jsonb("tag_ids").$type<string[]>().notNull().default([]),
    /** Rights/licensing (LIB-002). Publishing is blocked after expiry. */
    rightsNote: text("rights_note"),
    rightsExpiresAt: timestamp("rights_expires_at", { withTimezone: true }),
    /** Whether the licence covers organic posting, paid usage, or both. */
    rightsScope: text("rights_scope").$type<RightsScope>().notNull().default("both"),
    /**
     * What this asset can be handed to a model AS, or null for most things.
     *
     * `product` is the one that matters: Sora's reference image becomes the
     * literal FIRST FRAME of the clip, so flagging the real packshot is what
     * puts the real product on screen instead of a plausible lookalike.
     * lib/media/references.ts already knows the priority order between kinds.
     */
    referenceKind: text("reference_kind").$type<ReferenceKind>(),
    /** Made by a model rather than captured. Drives the synthetic-media disclosure suggestion. */
    generatedByAi: boolean("generated_by_ai").notNull().default(false),
    generationModel: text("generation_model"),
    /** The job that made it — closes the loop from an asset back to its model, spec and cost. */
    mediaJobId: text("media_job_id"),
    /** A captioned render points at its source; a 9:16 cut at the 16:9 it came from. */
    derivedFromAssetId: text("derived_from_asset_id"),
    /**
     * What survived our own pipeline. Re-encoding STRIPS C2PA, so this records
     * what arrived and what we re-signed — never silently losing the disclosure
     * the model vendor attached (EU AI Act Art. 50).
     */
    provenance: jsonb("provenance").$type<AssetProvenance>(),
    /** Where the rights come from. Decides which networks may carry it. */
    licenseSource: text("license_source").$type<LicenseSource>().notNull().default("owned"),
    /**
     * Per-network clearance. Meta Sound Collection is cleared for Facebook and
     * Instagram ONLY; TikTok's Commercial Music Library for TikTok only. An
     * empty object means "not restricted"; a false entry blocks that network.
     */
    platformClearance: jsonb("platform_clearance").$type<Record<string, boolean>>().notNull().default({}),
    uploadStatus: uploadStatus("upload_status").notNull().default("pending"),
    scanStatus: scanStatus("scan_status").notNull().default("pending"),
    scanNote: text("scan_note"),
    processingError: text("processing_error"),
    uploadedByUserId: text("uploaded_by_user_id").references(() => user.id, { onDelete: "set null" }),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    createdAt: now("created_at"),
    updatedAt: now("updated_at"),
  },
  (t) => [
    index("asset_ws_created_idx").on(t.workspaceId, t.createdAt),
    index("asset_ws_kind_idx").on(t.workspaceId, t.kind),
    uniqueIndex("asset_storage_key_idx").on(t.storageKey),
  ],
);

export const RENDITION_KINDS = ["thumb", "preview", "web", "poster", "captions", "waveform"] as const;
export type RenditionKind = (typeof RENDITION_KINDS)[number];

export const assetRendition = pgTable(
  "asset_rendition",
  {
    id: id(),
    assetId: text("asset_id").notNull().references(() => asset.id, { onDelete: "cascade" }),
    kind: text("kind").$type<RenditionKind>().notNull(),
    storageKey: text("storage_key").notNull(),
    mimeType: text("mime_type").notNull(),
    width: integer("width"),
    height: integer("height"),
    bytes: integer("bytes"),
    /**
     * What survived OUR re-encode, probed from the bytes we produced. Publishing
     * sends the rendition, not the original, so this — not the asset's own
     * provenance — is what the credential warning must describe. Null on rows
     * written before this was recorded.
     */
    credential: text("credential").$type<AssetProvenance["c2pa"]>(),
    createdAt: now("created_at"),
  },
  (t) => [uniqueIndex("asset_rendition_asset_kind_idx").on(t.assetId, t.kind)],
);

/**
 * Candidate cover frames for a video, pulled on request (`asset.frames`), one row
 * per offset. The CHOSEN frame lives on the post variant, not here: the same clip
 * can carry a different cover on each channel.
 */
export const assetFrame = pgTable(
  "asset_frame",
  {
    id: id(),
    organizationId: text("organization_id").notNull().references(() => organization.id, { onDelete: "cascade" }),
    workspaceId: text("workspace_id").notNull().references(() => workspace.id, { onDelete: "cascade" }),
    assetId: text("asset_id").notNull().references(() => asset.id, { onDelete: "cascade" }),
    offsetMs: integer("offset_ms").notNull(),
    storageKey: text("storage_key").notNull(),
    mimeType: text("mime_type").notNull(),
    width: integer("width"),
    height: integer("height"),
    bytes: integer("bytes"),
    createdAt: now("created_at"),
  },
  (t) => [uniqueIndex("asset_frame_asset_offset_idx").on(t.assetId, t.offsetMs), index("asset_frame_ws_idx").on(t.workspaceId)],
);

export type Asset = typeof asset.$inferSelect;
export type AssetRendition = typeof assetRendition.$inferSelect;
export type AssetFrame = typeof assetFrame.$inferSelect;
export type Folder = typeof folder.$inferSelect;
export type Tag = typeof tag.$inferSelect;
